import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const ALLOWED_ORIGINS=new Set(["https://yuubae96-rgb.github.io"]);
const VOICES=new Set(["Charon","Gacrux","Sadaltager","Iapetus","Algieba","Schedar","Kore","Aoede","Sulafat","Vindemiatrix","Achernar","Puck"]);
const cors=(req:Request)=>{const o=req.headers.get("origin")||"";return{"Access-Control-Allow-Origin":ALLOWED_ORIGINS.has(o)?o:"","Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"}};
const json=(d:unknown,s:number,h:Record<string,string>)=>new Response(JSON.stringify(d),{status:s,headers:{...h,"Content-Type":"application/json"}});
function interactionText(d:any){const out:string[]=[];for(const s of d?.steps||[])if(s?.type==="model_output")for(const i of s?.content||[])if(i?.type==="text"&&i?.text)out.push(i.text);return out.join("\n\n")}
function interactionContent(d:any,t:string){for(const s of d?.steps||[])if(s?.type==="model_output")for(const i of s?.content||[])if(i?.type===t)return i;return null}
function openaiText(d:any){if(typeof d?.output_text==="string"&&d.output_text)return d.output_text;const out:string[]=[];for(const o of d?.output||[])for(const c of o?.content||[])if((c?.type==="output_text"||c?.type==="text")&&c?.text)out.push(c.text);return out.join("\n\n")}
function parseDataUrl(s:string){const m=s.match(/^data:([^;]+);base64,(.+)$/s);return m?{mimeType:m[1],data:m[2]}:null}
function wavToRawPcmBase64(b64:string){const bin=atob(b64),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);if(bytes.length<12||String.fromCharCode(...bytes.subarray(0,4))!=="RIFF")return b64;const dv=new DataView(bytes.buffer);let off=12;while(off+8<=bytes.length){const id=String.fromCharCode(...bytes.subarray(off,off+4));const size=dv.getUint32(off+4,true);if(id==="data"){const raw=bytes.subarray(off+8,Math.min(bytes.length,off+8+size));let s="";for(let i=0;i<raw.length;i+=32768)s+=String.fromCharCode(...raw.subarray(i,i+32768));return btoa(s)}off+=8+size+(size%2)}return b64}
function prependSilenceToRawPcmBase64(b64:string,sr=24000,ch=1,ms=900){const bin=atob(b64),raw=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)raw[i]=bin.charCodeAt(i);const silenceBytes=Math.round(sr*ch*2*ms/1000),out=new Uint8Array(silenceBytes+raw.length);out.set(raw,silenceBytes);let s="";for(let i=0;i<out.length;i+=32768)s+=String.fromCharCode(...out.subarray(i,i+32768));return btoa(s)}
function pcm16ToWavBase64(b:string,sr=24000,ch=1){const bin=atob(b),pcm=new Uint8Array(bin.length),hd=new ArrayBuffer(44),dv=new DataView(hd),u=new Uint8Array(hd),w=(o:number,s:string)=>{for(let i=0;i<s.length;i++)u[o+i]=s.charCodeAt(i)};for(let i=0;i<bin.length;i++)pcm[i]=bin.charCodeAt(i);w(0,"RIFF");dv.setUint32(4,36+pcm.length,true);w(8,"WAVE");w(12,"fmt ");dv.setUint32(16,16,true);dv.setUint16(20,1,true);dv.setUint16(22,ch,true);dv.setUint32(24,sr,true);dv.setUint32(28,sr*ch*2,true);dv.setUint16(32,ch*2,true);dv.setUint16(34,16,true);w(36,"data");dv.setUint32(40,pcm.length,true);const out=new Uint8Array(44+pcm.length);out.set(u);out.set(pcm,44);let s="";for(let i=0;i<out.length;i+=32768)s+=String.fromCharCode(...out.subarray(i,i+32768));return btoa(s)}

const imageTimes:number[]=[];
function imageRateGuard(){const now=Date.now(),cut=now-10*60*1000;while(imageTimes.length&&imageTimes[0]<cut)imageTimes.shift();if(imageTimes.length>=20)throw new Error("安全装置：画像生成が10分間に20回を超えたため停止しました。しばらく待ってから必要なシーンだけ生成してください。");imageTimes.push(now)}

function scriptTask(b:any){const topic=String(b.topic||"").trim().slice(0,400),extra=String(b.extra||"").trim().slice(0,3000),urls=(Array.isArray(b.referenceUrls)?b.referenceUrls:[]).map((x:any)=>String(x).trim()).filter((x:string)=>/^https?:\/\//i.test(x)).slice(0,5),minutes=Math.min(10,Math.max(1,Number(b.minutes||3))),aspectRatio=String(b.aspectRatio)==="9:16"?"9:16":"16:9";if(!topic&&!urls.length)throw new Error("テーマまたは参考URLを入力してください。");const n=minutes<=1?6:minutes<=3?10:minutes<=5?14:18;const task=`日本語YouTube歴史ドキュメンタリーの構成を作成してください。テーマ「${topic||"参考資料を中心に決める"}」、約${minutes}分、全${n}シーン。${aspectRatio==="9:16"?'YouTubeショート用9:16縦動画。':'YouTube通常用16:9横動画。'}\n追加指示: ${extra||"なし"}\n${urls.length?'参考URL:\n'+urls.join('\n'):''}\n史実と推測を分け、各シーンの画像指示は年代・場所・人物・服装・建築・光・構図まで具体的に。時代錯誤を避ける。JSONだけを返す。形式:{"title":"動画タイトル","summary":"短い概要","scenes":[{"title":"短いシーン名","narration":"日本語ナレーション","imagePrompt":"詳細な日本語の画像指示","factCheck":"史実上の注意点"}]}`;return{task,urls}}
async function openaiScript(b:any,key:string){const {task}=scriptTask(b);const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-terra",input:task,reasoning:{effort:"medium"},text:{verbosity:"medium"}})}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||`OpenAI 構成生成エラー ${r.status}`);const text=openaiText(d).trim().replace(/^```json\s*/i,"").replace(/```$/i,"").trim();let p;try{p=JSON.parse(text)}catch{throw new Error("OpenAI returned invalid JSON")};p._provider="openai";return p}
async function geminiScript(b:any,key:string){const {task,urls}=scriptTask(b);const input:any[]=[{type:"text",text:task}];for(const u of urls)input.push(/(?:youtube\.com|youtu\.be)/i.test(u)?{type:"video",uri:u}:{type:"text",text:`参考Webページ: ${u}`});const payload:any={model:"gemini-3.8-flash",input};if(urls.some((u:string)=>!/(?:youtube\.com|youtu\.be)/i.test(u)))payload.tools=[{type:"url_context"}];const r=await fetch("https://generativelanguage.googleapis.com/v1beta/interactions",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||`Gemini 構成生成エラー ${r.status}`);const text=interactionText(d).trim().replace(/^```json\s*/i,"").replace(/```$/i,"").trim();let p;try{p=JSON.parse(text)}catch{throw new Error("Gemini returned invalid JSON")};p._provider="gemini-fallback";return p}

const JAPANESE_IMAGE_TEXT_RULE="【画像内文字・必須】画像内の見出し、図解ラベル、吹き出し、説明、看板、新聞、書類の文字は、すべて日本語（漢字・ひらがな・カタカナ）で描く。英語のラベルや英文、意味不明なアルファベットは描かない。元の場面指示や参考画像に英語があっても日本語に訳し、参考画像の英語は引き継がない。正式な社名・商標として不可欠な英字と数字・年号だけは例外。文字は短く正確で読みやすい日本語に絞る。例：CULTURAL IMPACT→企業文化への影響、IMPOSSIBLE GOALS→無理な目標、FIELD OPERATIONS→現場、INVESTIGATIVE REPORT→調査報告書、Risk→危険、Auditing firm→監査法人。日本語で正確に描けない説明は英語で代用せず省略する。動画タイトル・字幕は描かない。";
function basePrompt(scene:string,aspectRatio:string,styleLabel=""){const frame=aspectRatio==="9:16"?"縦型9:16の構図。":"横型16:9の構図。";const label=String(styleLabel||"").slice(0,100);if(label==="手描き歴史図解・学習ポスター風")return `日本語の手描き歴史図解・学習ポスター。写真や実写にはしない。温かいクリーム色の紙、水彩と色鉛筆の陰影、明瞭なペンの輪郭。場面の人物・場所・図表・矢印・地図を、内容が伝わる学習ポスターとして配置する。場面指示に写真・リアルな映画などが含まれていても、題材と動作だけを採用して手描きイラストにする。重要な絵は画面内に収める。${frame}\n【この場面の内容】\n${scene}\n\n${JAPANESE_IMAGE_TEXT_RULE}`;return `Photorealistic live-action historical cinema. Historical accuracy is mandatory: period-correct clothing, hairstyles, architecture, weapons, tools and landscape. No illustration, anime, manga, cartoon, added text, lettering, logos or watermarks. ${frame}\nSCENE CONTENT: ${scene}\n\n${JAPANESE_IMAGE_TEXT_RULE}\n実写風の画像には図解用の説明文字を追加しない。`}
async function openaiImage(scene:string,aspectRatio:string,key:string,styleLabel=""){const r=await fetch("https://api.openai.com/v1/images/generations",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-image-2",prompt:basePrompt(scene,aspectRatio,styleLabel),size:aspectRatio==="9:16"?"1024x1536":"1536x1024",quality:"medium",output_format:"jpeg",n:1})}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||`OpenAI 画像生成エラー ${r.status}`);const data=d?.data?.[0]?.b64_json;if(!data)throw new Error("OpenAI画像データを取得できませんでした。");return{mimeType:"image/jpeg",data,provider:"openai",model:"gpt-image-2",quality:"medium"}}
async function geminiImage(b:any,key:string){imageRateGuard();const scene=String(b.prompt||"").trim().slice(0,7000),aspectRatio=String(b.aspectRatio)==="9:16"?"9:16":"16:9",protagonist=parseDataUrl(String(b.protagonistReference||"")),styleRef=parseDataUrl(String(b.styleReference||"")),sceneRef=parseDataUrl(String(b.sceneReference||""));if(!scene)throw new Error("画像指示がありません。");const parts:any[]=[];if(sceneRef){parts.push({text:"Current scene reference. Preserve background, composition and lighting as closely as possible."},{inlineData:{mimeType:sceneRef.mimeType,data:sceneRef.data}})}if(protagonist){parts.push({text:"Protagonist reference. Preserve the person's recognizable identity when the protagonist appears."},{inlineData:{mimeType:protagonist.mimeType,data:protagonist.data}})}if(styleRef){parts.push({text:"Style reference only. Match color, lighting and texture; do not copy subject matter."},{inlineData:{mimeType:styleRef.mimeType,data:styleRef.data}})}parts.push({text:basePrompt(scene,aspectRatio,String(b.styleLabel||""))});const r=await fetch("https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-image:generateContent",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},body:JSON.stringify({contents:[{parts}],generationConfig:{responseModalities:["TEXT","IMAGE"],imageConfig:{aspectRatio,imageSize:"1K"}}})}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||`Gemini画像生成エラー ${r.status}`);const out=(d?.candidates||[]).flatMap((c:any)=>c?.content?.parts||[]),img=out.find((p:any)=>p?.inlineData?.data||p?.inline_data?.data),inline=img?.inlineData||img?.inline_data;if(!inline?.data)throw new Error("画像データを取得できませんでした。");return{mimeType:inline.mimeType||inline.mime_type||"image/jpeg",data:inline.data,provider:"gemini"}}

Deno.serve(async(req:Request)=>{const h=cors(req);if(req.method==="OPTIONS")return new Response("ok",{headers:h});if(!ALLOWED_ORIGINS.has(req.headers.get("origin")||""))return json({error:"Forbidden origin"},403,h);try{const b=await req.json(),action=String(b.action||""),geminiKey=Deno.env.get("GEMINI_API_KEY")||"",openaiKey=Deno.env.get("OPENAI_API_KEY")||"";
if(action==="generateScript"){const requested=String(b.provider||b.scriptProvider||"openai").toLowerCase();const billingErr=(e:any)=>/402|429|payment|required|billing|credit|quota|no credits remaining|insufficient_quota/i.test(String(e?.message||e));if(requested==="gemini"&&geminiKey){try{return json(await geminiScript(b,geminiKey),200,h)}catch(e){console.error("Gemini script failed:",e);if(billingErr(e)&&openaiKey){try{return json(await openaiScript(b,openaiKey),200,h)}catch(oe){console.error("OpenAI also unavailable:",oe);throw e}}throw e}}if(openaiKey){try{return json(await openaiScript(b,openaiKey),200,h)}catch(e){console.error("OpenAI script failed:",e);if(geminiKey&&(billingErr(e)||requested==="openai")){try{return json(await geminiScript(b,geminiKey),200,h)}catch(ge){console.error("Gemini fallback also unavailable:",ge);throw e}}throw e}}if(geminiKey)return json(await geminiScript(b,geminiKey),200,h);throw new Error("AI API key is not configured")}
if(action==="generateImage"){const scene=String(b.prompt||"").trim().slice(0,7000),aspectRatio=String(b.aspectRatio)==="9:16"?"9:16":"16:9",imageProvider=String(b.imageProvider||"gemini");if(!scene)throw new Error("画像指示がありません。");const hasRefs=!!(b.protagonistReference||b.styleReference||b.sceneReference||b.refineMode);if(imageProvider==="gemini"||hasRefs){if(!geminiKey)throw new Error("Gemini画像APIが設定されていません。");return json(await geminiImage(b,geminiKey),200,h)}if(imageProvider==="openai"){if(!openaiKey)throw new Error("OpenAI画像APIが設定されていません。");return json(await openaiImage(scene,aspectRatio,openaiKey,String(b.styleLabel||"")),200,h)}throw new Error("画像生成AIの指定が不正です。")}
if(action==="generateTts"){if(!geminiKey)throw new Error("GEMINI_API_KEY is not configured");const text=String(b.text||"").trim().slice(0,12000),requestedModel=String(b.model||"gemini-3.8-flash-lite-tts"),ttsModel=requestedModel==="gemini-3.8-flash-tts"?"gemini-3.8-flash-tts":"gemini-3.8-flash-lite-tts",rq=String(b.voice||"Kore"),voice=VOICES.has(rq)?rq:"Kore",direction=String(b.direction||"落ち着いた日本語の歴史ドキュメンタリー調。自然な間、明瞭な発音、ややゆっくり。").slice(0,500);if(!text)throw new Error("読み上げる文章がありません。");const r=await fetch("https://generativelanguage.googleapis.com/v1beta/interactions",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":geminiKey},body:JSON.stringify({model:ttsModel,input:[{type:"user_input",content:[{type:"text",text,annotations:[{type:"speech_metadata",style:direction}]}]}],response_format:{type:"audio"},generation_config:{speech_config:[{voice}]}})}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||`音声生成エラー ${r.status}`);const a=d?.output_audio||interactionContent(d,"audio");if(!a?.data)throw new Error("音声データを取得できませんでした。");const mime=String(a.mime_type||a.mimeType||"audio/wav");const raw=mime.includes("wav")?wavToRawPcmBase64(a.data):a.data,withSilence=prependSilenceToRawPcmBase64(raw,24000,1,900);return json({mimeType:"audio/wav",data:pcm16ToWavBase64(withSilence,24000,1),voice,leadingSilenceMs:900,provider:"google",model:ttsModel},200,h)}
return json({error:"Unknown action"},400,h)}catch(e){return json({error:String((e as any)?.message||e)},500,h)}});
